[package]
name = "mmcp"
version = "0.1.0"
authors = ["Andreas Schmidt <info@portal-as.de>"]
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes", "unstable"] }
color-eyre = "0.6.2"
num-format = "0.4"
prettytable-rs = "^0.10"
rand = "0.8"
structopt = "0.3"